# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'session.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_session(object):
    def setupUi(self, session):
        session.setObjectName("session")
        session.resize(800, 300)
        session.setMinimumSize(QtCore.QSize(800, 300))
        session.setWindowOpacity(0.9)
        session.setStyleSheet("background-color: rgb(26, 26, 26);\n"
"font: \"IosevkaTerm Nerd Font\";")
        self.centralwidget = QtWidgets.QWidget(session)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(100, 100, 100);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_close = QtWidgets.QPushButton(self.frame)
        self.bt_close.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon)
        self.bt_close.setIconSize(QtCore.QSize(30, 30))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout.addWidget(self.bt_close)
        spacerItem = QtWidgets.QSpacerItem(731, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("QPlainTextEdit{\n"
"    background-color: rgb(204, 204, 204);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0,0,0);\n"
"    border-radius: 20%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(133, 0, 104)\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.sesion_text = QtWidgets.QPlainTextEdit(self.frame_2)
        self.sesion_text.setMinimumSize(QtCore.QSize(700, 150))
        self.sesion_text.setMaximumSize(QtCore.QSize(700, 250))
        self.sesion_text.setObjectName("sesion_text")
        self.gridLayout.addWidget(self.sesion_text, 0, 0, 1, 1)
        self.bt_send = QtWidgets.QPushButton(self.frame_2)
        self.bt_send.setMinimumSize(QtCore.QSize(70, 50))
        font = QtGui.QFont()
        font.setFamily("IosevkaTerm Nerd Font")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bt_send.setFont(font)
        self.bt_send.setObjectName("bt_send")
        self.gridLayout.addWidget(self.bt_send, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        session.setCentralWidget(self.centralwidget)

        self.retranslateUi(session)
        QtCore.QMetaObject.connectSlotsByName(session)

    def retranslateUi(self, session):
        _translate = QtCore.QCoreApplication.translate
        session.setWindowTitle(_translate("session", "MainWindow"))
        self.bt_send.setText(_translate("session", "󱅥"))
